version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 3002
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      ERP_SERVER: ${ERP_SERVER}
      ERP_PORT: ${ERP_PORT}
      ERP_DATABASE: ${ERP_DATABASE}
      ERP_USER: ${ERP_USER}
      ERP_PASSWORD: ${ERP_PASSWORD}
    networks:
      - app-network
    ports:
      - "3002:3002"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
